name: common_microbe

channels:
- conda-forge
dependencies:
- conda-forge::python=3.7
- conda-forge::numpy=1.19.5
- conda-forge::pandas=0.23.4
- conda-forge::seaborn=0.11.1
- conda-forge::umap-learn=0.4.2
- conda-forge::numba=0.50.1
- conda-forge::plotnine=0.5.1
- conda-forge::jupyter
- conda-forge::ipykernel=5.1.1
- conda-forge::nb_conda_kernels
- pip=19.2.1
- pip:
  - matplotlib==3.0.0
  - ponyo==0.6
  - black==20.8b1
  - flake8==3.8.4
  - pre_commit==2.9.3
  - jupytext==1.9.1
  - pynndescent
